### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yesyeahvh123** [DrDRR/RenPy-UnAPK#1]
i get this error how to fix? thanks
 line 6, in <module>
    from unrpyc import *
ModuleNotFoundError: No module named 'unrpyc'

**Comment by drdrr** [comment]
Hi! I've uploaded unrpyc dependency (alternatively you could download madeddy's [unrpyc](https://github.com/madeddy/unrpyc) and place `renpy-unapk.py` in its folder to run this script). 
The sript should work with a simple `python renpy-unapk.py` now.

> i get this error how to fix? thanks line 6, in from unrpyc import * ModuleNotFoundError: No module named 'unrpyc'

**Comment by yesyeahvh123** [comment]
@DrDRR Sir i got this problem, can you tell me how to fix it?thanks
Decompiling My Dear Prince\game\scripts\art.rpyc to My Dear Prince\game\scripts\art.rpy...
Error while decompiling My Dear Prince\game\scripts\art.rpyc:
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\RenPy-UnAPK-main\RenPy-UnAPK-main\unrpyc.py", line 223, in worker
    return decompile_rpyc(filename, args.clobber, args.dump, decompile_python=args.decompile_python,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Downloads\RenPy-UnAPK-main\RenPy-UnAPK-main\unrpyc.py", line 187, in decompile_rpyc
    ast = read_ast_from_file(in_file)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Downloads\RenPy-UnAPK-main\RenPy-UnAPK-main\unrpyc.py", line 160, in read_ast_from_file
    data, stmts = revertable_switch(raw_contents)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Downloads\RenPy-UnAPK-main\RenPy-UnAPK-main\unrpyc.py", line 129, in revertable_switch
    data, stmts = magic.safe_loads(raw_dat, cls_factory_74, {
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Downloads\RenPy-UnAPK-main\RenPy-UnAPK-main\decompiler\magic.py", line 604, in safe_loads
    encoding=encoding, errors=errors).load()
                                      ^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\pickle.py", line 1681, in load_appends
    append = list_obj.append
             ^^^^^^^^^^^^^^^
AttributeError: 'RevertableList' object has no attribute 'append'

**Comment by yesyeahvh123** [comment]
https://workupload.com/file/ReRN6UBFtaj art.rpyc

**Comment by yesyeahvh123** [comment]
@DrDRR can you use this? I find it decoding very well
[UnRen-1.0.10b.zip](https://github.com/DrDRR/RenPy-UnAPK/files/11372226/UnRen-1.0.10b.zip)
